### PR TITLE
Issue/responsive design

### PR DESCRIPTION
**Pull request by DaniMaci**

### CODE REVIEW

**Comment by CVelazquezURJC** [comment]
I change script location in login.html

**Comment by DaniMaci** [comment]
ok, perfect

**Comment by Hgmoa** [comment]
OKay, only missing shop responsive design now!

**Comment by Hgmoa** [comment]
All changes done?

**Comment by RamonSpain** [comment]
Good job

**Comment by Hgmoa** [comment]
Fixed #32

**Comment by Hgmoa** [comment]
Ups, merged now!

**Pull request merged**
