### PR TITLE
Edited dashboard index page

### PR DESCRIPTION
**Pull request by Hgmoa**
Any suggestion to add to index page?

### CODE REVIEW

**Comment by Hgmoa** [comment]
Any suggestion to add to index page?

**Comment by JorgeGalingP** [comment]
Looks good but maybe we need to add a map for the house, corporative image or something like that to fill the remain space.

**Comment by Hgmoa** [comment]
What else can i add or change?

**Comment by CVelazquezURJC** [comment]
yes, can do it.

**Pull request merged**
