### PR TITLE
changes in the index

### PR DESCRIPTION
**Pull request by DaniMaci**
- tab icon
   - tab name
   - definitions and picter of index

### CODE REVIEW

**Review by Hgmoa — CHANGES_REQUESTED** [review]
Misspelled login.html page title

**Review by Hgmoa — APPROVED** [review]

**Comment by Hgmoa** [comment]
I think all is ok! Let's merge!

**Comment by JorgeGalingP** [comment]
Good work!

**Comment by DaniMaci** [comment]
I continue whith the index

**Comment by DaniMaci** [comment]
Fixes #22

**Comment by DaniMaci** [comment]
insert product page in index

**Pull request merged**
